In [ ]:
# cross validation(k fold)-reduce overfitting 

In [9]:
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold,train_test_split,cross_val_score

In [3]:
data ={'Age':[20,25,23,21,29,28,26],'salary':[26,30,27,22,25,30,32]}

In [5]:
newdata=pd.DataFrame(data,columns=['Age','salary'])

In [6]:
newdata

Age  salary
0   20      26
1   25      30
2   23      27
3   21      22
4   29      25
5   28      30
6   26      32

In [7]:
kf = KFold(n_splits=3)

In [8]:
for x,y in kf.split(newdata[['Age']]):
    print(x,y)

[3 4 5 6] [0 1 2]
[0 1 2 5 6] [3 4]
[0 1 2 3 4] [5 6]
