In [11]:
import pandas as pd 
import numpy as np 
from sklearn.naive_bayes import GaussianNB , MultinomialNB , BernoulliNB
from sklearn.preprocessing import OrdinalEncoder
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split 
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
data = pd.read_csv('NaveSpamornot.csv')

In [3]:
data

Category                 Msg
0      Ham        Do,your best
1      Ham  I m looking for it
2     Spam         Free,reward
3      Ham        This is good
4      Ham   Hope u can get it
5     Spam      discount,offer

In [16]:
ords = OrdinalEncoder(categories=[['Spam','Ham']],dtype=np.int32)


In [20]:
data['category']=ords.fit_transform(data[['Category']])

In [21]:
data

Category                 Msg  category
0      Ham        Do,your best         1
1      Ham  I m looking for it         1
2     Spam         Free,reward         0
3      Ham        This is good         1
4      Ham   Hope u can get it         1
5     Spam      discount,offer         0

In [22]:
x= data['Msg']
x

0          Do,your best
1    I m looking for it
2           Free,reward
3          This is good
4     Hope u can get it
5        discount,offer
Name: Msg, dtype: object

In [23]:
y= data['Category']
y

0     Ham
1     Ham
2    Spam
3     Ham
4     Ham
5    Spam
Name: Category, dtype: object

In [35]:
v= CountVectorizer()


In [36]:
xnew=v.fit_transform(x)

In [37]:
print(v.get_feature_names_out())

['best' 'can' 'discount' 'do' 'for' 'free' 'get' 'good' 'hope' 'is' 'it'
 'looking' 'offer' 'reward' 'this' 'your']


In [38]:
print(v.vocabulary_)

{'do': 3, 'your': 15, 'best': 0, 'looking': 11, 'for': 4, 'it': 10, 'free': 5, 'reward': 13, 'this': 14, 'is': 9, 'good': 7, 'hope': 8, 'can': 1, 'get': 6, 'discount': 2, 'offer': 12}


In [39]:
print(xnew.toarray())

[[1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0]
 [0 1 0 0 0 0 1 0 1 0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0]]


In [40]:
xtrain,xtest,ytrain,ytest = train_test_split(xnew,y,test_size=0.2,random_state=3)

In [41]:
mb = MultinomialNB()

In [42]:
mb.fit(xtrain,ytrain)

MultinomialNB()

In [43]:
mb.predict(v.transform(['free,offer']))

array(['Spam'], dtype='<U4')